### ISSUE TITLE
Plugin Bikes test product page redesign

### ISSUE THREAD

**Issue by jabberdog** [jabberdog/PluginBikes#2]
Hi,

So on a test product page on Plugin Bikes lets try and re-style the area with the price & order block (right side block) by having a similar style like we now have on Wholesale product page.
On plugin bikes keep the add to cart button as green.

Example of how looks that block on Wled:
https://www.wholesaleledlights.co.uk/moroccan-ball-table-lamp.html

Thanks,

Florin

**Comment by Florinnn** [comment]
Hi Ben,

I have prepared a sample of how the product page on Pluginbikes (see the attachment) should look like so please when starting to work on it use the attached printscreen.

I should also mention that in the area with the specs table you can choose to style it differently more fancier than in my sample image. So feel free to come up with your ideas and let me know too on the go which solutions do you plan to choose for a specific part in the page so that we can ensure in the end we get to a good point.

I'm open to test and try different colours and styles so please get back to me as you progress with it so that we can both ensure we go in the right direction with it.

Thanks,
Florin
![PB_5.jpg](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/PB_5-af6f2e8c5a765f8a719aae53d8e4350804d4c7ccefe71e57025171f95f63ec39.jpg)
